import pygame as pg

## SCREEN DATA ##
SCREEN_WIDTH, SCREEN_HEIGHT = 1200, 700
SCREEN = pg.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
BG_COLOR = (0, 0, 0)

## SIMULATION SPEED ##
CLOCK = pg.time.Clock()
FPS = 30

## LOOP CONDITION ##
SIM_LOOP = True

## FLUID DATA ##
USE_SHG = True
NUM_PARTICLES = 1000
ENERGY_LOSS = 0.9
GRAVITY = 1
GRID_COLOR = (255, 255, 255)

## PARTICLE DATA ##
MASS = 1.0
RADIUS = 8.0
PLANET_LIKE = False
PLANET_CENTER = [SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2]

## UI ##
FONT_FAMILY = "arial"
FONT_SIZE = 20
FONT_COLOR = (255, 255, 255)
BUTTON_HOVERED_COLOR = (255, 0, 0)